spring:
  datasource:
    test1:
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8
      driverClassName: com.mysql.cj.jdbc.Driver
      username: 用户名
      password: 密码
    test2:
      jdbc-url: jdbc:sqlserver://ip:端口;DatabaseName=数据库名
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: 用户名
      password: 密码

mybatis:
  mapper-locations: classpath:mapper/**.xml